DATABASE_HOST: "127.0.0.1"
DATABASE_PORT: "3306"
DATABASE_USER: "root"
DATABASE_PASS: "1"
DATABASE_NAME: "book_review"
SMTP_HOST: "localhost:3000"
SMTP_ADDRESS: "smtp.gmail.com"
SMTP_PORT: "587"
SMTP_EMAIL: "huuco2401@gmail.com"
SMTP_PASSWORD: "ymdosmzxyyyspwwb"
SMTP_DOMAIN: "gmail.com"
